name: Publish packages on PyPI

on:
  workflow_dispatch:
    inputs:
      publish-package:
        description: "Build or Build and Publish?"
        required: true
        type: choice
        default: "Build"
        options:
          - "Build"
          - "Build and Publish"
      publish-destination:
        description: "Publish to PyPI or TestPyPI?"
        required: true
        type: choice
        default: "TestPyPI"
        options:
          - "TestPyPI"
          - "PyPI"

permissions: {}

jobs:
  downloadbinaries:
    runs-on: ubuntu-latest
    outputs:
      package-version: ${{ steps.package.outputs.package-version }}
      serverless-compat-version: ${{ steps.serverlesscompatbinary.outputs.serverless-compat-version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: package
        run: |
          if [[ ! "$GITHUB_REF" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format: $GITHUB_REF, must be in the form vMAJOR.MINOR.PATCH"
            exit 1
          fi
          PACKAGE_VERSION="${GITHUB_REF#refs/tags/v}"

          echo "package-version=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
      - id: serverlesscompatbinary
        run: |
          RESPONSE=$(curl -s "https://api.github.com/repos/datadog/serverless-components/releases")
          SERVERLESS_COMPAT_VERSION=$(echo "$RESPONSE" | jq -r --arg pattern "datadog-serverless-compat\/v[0-9]*\.[0-9]*\.[0-9]*" '.[] | select(.tag_name | test($pattern)) | .tag_name' | sort -V | tail -n 1)

          echo "Using version ${SERVERLESS_COMPAT_VERSION} of Serverless Compatibility Layer binary"
          echo "serverless-compat-version=$(echo "$SERVERLESS_COMPAT_VERSION" | jq -rR 'ltrimstr("sls-")')" >> "$GITHUB_OUTPUT"

          curl --output-dir ./temp/ --create-dirs -O -s -L "https://github.com/DataDog/serverless-components/releases/download/${SERVERLESS_COMPAT_VERSION}/datadog-serverless-compat.zip"
          unzip ./temp/datadog-serverless-compat.zip -d ./datadog_serverless_compat
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: bin
          path: datadog_serverless_compat/bin
  build:
    runs-on: ubuntu-latest
    needs: [downloadbinaries]
    env:
      PACKAGE_VERSION: ${{ needs.downloadbinaries.outputs.package-version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: datadog_serverless_compat
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.9 - 3.12"
      - uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: 1.8.5
      - run: poetry version ${{ env.PACKAGE_VERSION }}
      - run: poetry build
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: dist
          path: dist
  publish:
    if: ${{ github.event.inputs.publish-package == 'Build and Publish' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      - uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70 # v1.12.3
        with:
          packages-dir: dist/
          password: ${{ github.event.inputs.publish-destination == 'PyPI' && secrets.PYPI_SERVERLESS_COMPAT_API_TOKEN || secrets.PYPI_SERVERLESS_COMPAT_API_TOKEN_TEST }}
          repository-url: ${{ github.event.inputs.publish-destination == 'PyPI' && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
  release:
    if: ${{ github.event.inputs.publish-package == 'Build and Publish' && github.event.inputs.publish-destination == 'PyPI' }}
    runs-on: ubuntu-latest
    needs: [downloadbinaries, publish]
    permissions:
      contents: write
    env:
      PACKAGE_VERSION: ${{ needs.downloadbinaries.outputs.package-version }}
      SERVERLESS_COMPAT_VERSION: ${{ needs.downloadbinaries.outputs.serverless-compat-version }}
    steps:
      - uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        with:
          body: "Uses [${{ env.SERVERLESS_COMPAT_VERSION }}](https://github.com/DataDog/serverless-components/releases/tag/${{ env.SERVERLESS_COMPAT_VERSION }}) of the Serverless Compatibility Layer binary."
          draft: true
          tag_name: "v${{ env.PACKAGE_VERSION }}"
          generate_release_notes: true
          make_latest: true
